name = "PrintFileTree"
uuid = "083f6447-9a71-585a-bc2e-c0ad124fd6e4"
authors = ["Nathan Daly <nhdaly@gmail.com>"]
version = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
